/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCard: typeof import('./src/components/IconCard.vue')['default']
    SvgSprite: typeof import('./src/components/SvgSprite.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TInput: typeof import('tdesign-vue-next')['Input']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
